package com.monkfitness.app.animation

enum class Joint(val index: Int) {
    PELVIS(0),
    HIP_F(1),
    HIP_B(2),
    KNEE_F(3),
    ANKLE_F(4),
    HEEL_F(5),
    TOE_F(6),
    KNEE_B(7),
    ANKLE_B(8),
    HEEL_B(9),
    TOE_B(10),
    CHEST(11),
    SHOULDER_A(12),
    SHOULDER_P(13),
    ELBOW_A(14),
    HAND_A(15),
    WRIST_A(16),
    PALM_A(17),
    KNUCKLES_A(18),
    FINGERTIPS_A(19),
    ELBOW_P(20),
    HAND_P(21),
    WRIST_P(22),
    PALM_P(23),
    KNUCKLES_P(24),
    FINGERTIPS_P(25),
    NECK_END(26),
    HEAD_POS(27)
}
