package com.monkfitness.app.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "meal_cycles")
data class MealCycle(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val startDate: String,
    val durationDays: Int,
    val createdAt: Long,
    val isCompleted: Boolean = false,
    val autoGenerated: Boolean = false
)
