package com.monkfitness.app.data.local

/**
 * The statements SQLite actually holds for the version-7 database, verbatim from the SQL Room
 * generates for the eight legacy entities and the two Stage-1 adaptive ones
 * (`AppDatabase_Impl.createAllTables` in the generated source).
 *
 * A migration test needs a database to migrate *from*. Building the version-7 half from Room's own
 * DDL — rather than from the migrations that led to it — keeps the fixture honest: it is what a
 * device that has been running the shipped build carries, so whatever survives the upgrade in the
 * test is what survives on that device.
 */
internal object LegacyV7Schema {

    /** The ten tables the version-7 database contains, as Room creates them. */
    val TABLE_STATEMENTS: List<String> = listOf(
        "CREATE TABLE IF NOT EXISTS `user_progress` (`cycleNumber` INTEGER NOT NULL, `day` INTEGER NOT NULL, `isCompleted` INTEGER NOT NULL, `completionDate` INTEGER NOT NULL, `workoutType` TEXT NOT NULL, PRIMARY KEY(`cycleNumber`, `day`))",
        "CREATE TABLE IF NOT EXISTS `posture_session_progress` (`cycleNumber` INTEGER NOT NULL, `day` INTEGER NOT NULL, `isCompleted` INTEGER NOT NULL, `completionDate` INTEGER NOT NULL, `focusArea` TEXT NOT NULL, PRIMARY KEY(`cycleNumber`, `day`))",
        "CREATE TABLE IF NOT EXISTS `set_log` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `exerciseId` TEXT NOT NULL, `repsCompleted` INTEGER NOT NULL, `durationSeconds` INTEGER NOT NULL, `timestamp` INTEGER NOT NULL, `sessionDate` TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS `body_weight_log` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `weightKg` REAL NOT NULL, `date` TEXT NOT NULL)",
        "CREATE UNIQUE INDEX IF NOT EXISTS `index_body_weight_log_date` ON `body_weight_log` (`date`)",
        "CREATE TABLE IF NOT EXISTS `program_day_state` (`cycleNumber` INTEGER NOT NULL, `programDay` INTEGER NOT NULL, `isWorkoutDay` INTEGER NOT NULL, `isCompleted` INTEGER NOT NULL, `isMissed` INTEGER NOT NULL, `completedAt` INTEGER, PRIMARY KEY(`cycleNumber`, `programDay`))",
        "CREATE TABLE IF NOT EXISTS `meal_cycles` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `startDate` TEXT NOT NULL, `durationDays` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, `isCompleted` INTEGER NOT NULL, `autoGenerated` INTEGER NOT NULL)",
        "CREATE TABLE IF NOT EXISTS `meals` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `cycleId` INTEGER NOT NULL, `dayNumber` INTEGER NOT NULL, `programDay` INTEGER NOT NULL, `week` INTEGER NOT NULL, `dayType` TEXT NOT NULL, `mealTypeKey` TEXT NOT NULL, `mealProfile` TEXT NOT NULL, `templateId` TEXT NOT NULL, `ingredientData` TEXT NOT NULL, `calories` INTEGER NOT NULL, `proteinGrams` INTEGER NOT NULL, `optional` INTEGER NOT NULL, FOREIGN KEY(`cycleId`) REFERENCES `meal_cycles`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        "CREATE INDEX IF NOT EXISTS `index_meals_cycleId` ON `meals` (`cycleId`)",
        "CREATE UNIQUE INDEX IF NOT EXISTS `index_meals_cycleId_programDay_mealTypeKey` ON `meals` (`cycleId`, `programDay`, `mealTypeKey`)",
        "CREATE TABLE IF NOT EXISTS `shopping_items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `cycleId` INTEGER NOT NULL, `ingredientKey` TEXT NOT NULL, `totalAmount` INTEGER NOT NULL, FOREIGN KEY(`cycleId`) REFERENCES `meal_cycles`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        "CREATE INDEX IF NOT EXISTS `index_shopping_items_cycleId` ON `shopping_items` (`cycleId`)",
        "CREATE TABLE IF NOT EXISTS `family_progression_state` (`familyId` TEXT NOT NULL, `progressionLevel` INTEGER NOT NULL, `currentExerciseId` TEXT, `adaptationState` TEXT NOT NULL, `precedingProgressQualifyingWindows` INTEGER NOT NULL, `precedingRegressQualifyingWindows` INTEGER NOT NULL, `precedingHighRiskWindows` INTEGER NOT NULL, `recoveryQualifyingSessions` INTEGER NOT NULL, `eligibleSessionsSinceLastProgressionChange` INTEGER, `programRevision` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL, `policyVersion` INTEGER NOT NULL, PRIMARY KEY(`programRevision`, `familyId`))",
        "CREATE TABLE IF NOT EXISTS `adaptive_decision_record` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `familyId` TEXT NOT NULL, `programRevision` INTEGER NOT NULL, `cycleNumber` INTEGER NOT NULL, `programDay` INTEGER NOT NULL, `timestamp` INTEGER NOT NULL, `previousState` TEXT NOT NULL, `newState` TEXT NOT NULL, `actions` TEXT NOT NULL, `reasonCode` TEXT NOT NULL, `policyVersion` INTEGER NOT NULL)",
        "CREATE TABLE IF NOT EXISTS room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT)",
        "INSERT OR REPLACE INTO room_master_table (id,identity_hash) VALUES(42, 'a5aeaf5a669d0f822992dc24665fa95f')"
    )

    /**
     * The ten tables of the version-7 database. `room_master_table` is Room's own bookkeeping table
     * and is deliberately absent: it is not one of the database's entities, and Room rewrites its
     * identity hash after a successful upgrade.
     */
    val TABLES: List<String> = listOf(
        "user_progress",
        "posture_session_progress",
        "set_log",
        "body_weight_log",
        "program_day_state",
        "meal_cycles",
        "meals",
        "shopping_items",
        "family_progression_state",
        "adaptive_decision_record"
    )

    /** The two Stage-1 adaptive tables, which PR 2 must leave exactly as they are. */
    val STAGE_ONE_ADAPTIVE_TABLES: List<String> =
        listOf("family_progression_state", "adaptive_decision_record")

    /** The legacy table the target schema's set log must not reuse. */
    const val LEGACY_SET_LOG_TABLE: String = "set_log"
}
