package com.monkfitness.app.data.local

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.sql.SQLException
import java.time.LocalDate

/**
 * The upgrade a device actually performs: a populated version-7 database, the production migration,
 * and the rows that have to survive it.
 *
 * Everything here runs on a real SQLite engine (`SqliteTestDatabase`), so the claims are engine
 * claims: the ten shipped tables are still there afterwards, every representative legacy row still
 * holds exactly the values it held, the Stage-1 adaptive tables are still writable, and the fifteen
 * target tables carry the primary keys, foreign keys, delete actions and indices the architecture
 * requires — read back from `sqlite_master` and `pragma_*`, not restated from the migration's text.
 *
 * The blueprint is explicit that there is **no legacy program/history migration** (§30): this upgrade
 * adds the target schema and touches nothing else. No legacy row is reinterpreted as a Program, no
 * placeholder Program/Revision/Session is backfilled, and the legacy `set_log` is not repurposed as
 * the target set log.
 *
 * The chain a device runs is `7 → 8 → 9 → 10`: the target schema, then the schedule-frequency
 * correction (`docs/PROGRAM_SCHEDULE_FREQUENCY_CORRECTION.md`), then the Goal/Focus columns
 * (`docs/PROGRAM_GENERATED_PLANNER.md`) — each of the last two adding nullable columns to
 * `program_revision` and nothing else. Everything below executes the production migration objects in
 * that order, so the database under test is the one the app opens.
 */
class ProgramMigrationPreservationTest {

    private fun versionSevenDatabase(): SqliteTestDatabase {
        val database = SqliteTestDatabase.inMemory()
        database.execAll(LegacyV7Schema.TABLE_STATEMENTS)
        database.exec(
            "INSERT INTO `user_progress` (`cycleNumber`, `day`, `isCompleted`, `completionDate`, " +
                "`workoutType`) VALUES (2, 7, 1, 1700000000000, 'STRENGTH')"
        )
        database.exec(
            "INSERT INTO `posture_session_progress` (`cycleNumber`, `day`, `isCompleted`, " +
                "`completionDate`, `focusArea`) VALUES (2, 7, 1, 1700000000000, 'UPPER_BACK')"
        )
        database.exec(
            "INSERT INTO `set_log` (`exerciseId`, `repsCompleted`, `durationSeconds`, `timestamp`, " +
                "`sessionDate`) VALUES ('pushup', 12, 0, 1700000000000, '2026-09-14')"
        )
        database.exec(
            "INSERT INTO `body_weight_log` (`weightKg`, `date`) VALUES (78.5, '2026-09-14')"
        )
        database.exec(
            "INSERT INTO `program_day_state` (`cycleNumber`, `programDay`, `isWorkoutDay`, " +
                "`isCompleted`, `isMissed`, `completedAt`) VALUES (2, 7, 1, 1, 0, 1700000000000)"
        )
        database.exec(
            "INSERT INTO `meal_cycles` (`id`, `startDate`, `durationDays`, `createdAt`, " +
                "`isCompleted`, `autoGenerated`) VALUES (4, '2026-09-14', 14, 1700000000000, 0, 1)"
        )
        database.exec(
            "INSERT INTO `meals` (`id`, `cycleId`, `dayNumber`, `programDay`, `week`, `dayType`, " +
                "`mealTypeKey`, `mealProfile`, `templateId`, `ingredientData`, `calories`, " +
                "`proteinGrams`, `optional`) VALUES (9, 4, 1, 7, 2, 'TRAINING', 'breakfast', " +
                "'BALANCED', 'template-1', '[]', 620, 41, 0)"
        )
        database.exec(
            "INSERT INTO `shopping_items` (`id`, `cycleId`, `ingredientKey`, `totalAmount`) " +
                "VALUES (5, 4, 'oats', 700)"
        )
        database.exec(
            "INSERT INTO `family_progression_state` (`familyId`, `progressionLevel`, " +
                "`currentExerciseId`, `adaptationState`, `precedingProgressQualifyingWindows`, " +
                "`precedingRegressQualifyingWindows`, `precedingHighRiskWindows`, " +
                "`recoveryQualifyingSessions`, `eligibleSessionsSinceLastProgressionChange`, " +
                "`programRevision`, `updatedAt`, `policyVersion`) VALUES ('push-family', 2, " +
                "'pushup', 'HOLD', 1, 0, 0, 0, 3, 1, 1700000000000, 1)"
        )
        database.exec(
            "INSERT INTO `adaptive_decision_record` (`id`, `familyId`, `programRevision`, " +
                "`cycleNumber`, `programDay`, `timestamp`, `previousState`, `newState`, `actions`, " +
                "`reasonCode`, `policyVersion`) VALUES (3, 'push-family', 1, 2, 7, 1700000000000, " +
                "'HOLD', 'PROGRESS', 'INCREASE_STIMULUS', 'SUSTAINED_POSITIVE_PERFORMANCE', 1)"
        )
        return database
    }

    private fun migratedDatabase(): SqliteTestDatabase = versionNineDatabase().also { database ->
        // The deployed chain, in the order a device runs it.
        database.migrate(AppDatabase.MIGRATION_9_10)
        database.migrate(AppDatabase.MIGRATION_10_11)
        // §30 step 15: the retirement step.
        database.migrate(AppDatabase.MIGRATION_11_12)
        // Target slot semantic identity: nullable, additive, and no legacy backfill.
        database.migrate(AppDatabase.MIGRATION_12_13)
    }

    /** A populated **version-8** database: what a device that ran the target-schema release holds. */
    private fun versionEightDatabase(): SqliteTestDatabase =
        versionSevenDatabase().also { it.migrate(AppDatabase.MIGRATION_7_8) }

    /**
     * A populated **version-9** database: what a device that ran the schedule-frequency correction
     * holds, before the Goal/Focus columns exist.
     */
    private fun versionNineDatabase(): SqliteTestDatabase = versionEightDatabase().also { database ->
        database.migrate(AppDatabase.MIGRATION_8_9)
    }

    /** SQLite stores the DDL without `IF NOT EXISTS`, so both sides are put in that form. */
    private fun storedForm(sql: String): String =
        ProgramSchemaFixture.normalized(sql).replace("IF NOT EXISTS ", "")

    private fun tablesOf(database: SqliteTestDatabase): List<String> =
        database.tableNames().filterNot { it.startsWith("sqlite_") }.sorted()

    @Test
    fun theUpgradeEndsWithTheRetainedAndTheTargetTablesAndNothingElse() {
        val before = versionSevenDatabase()
        val after = migratedDatabase()

        assertEquals(
            "the version-7 database is exactly the ten shipped tables",
            (LegacyV7Schema.TABLES + "room_master_table").sorted(),
            tablesOf(before)
        )
        assertEquals(
            "after the whole chain the database is the five retained global tables and the fifteen " +
                "target ones — and nothing else. The other five shipped tables are dropped by §30 " +
                "step 15, and no table stands in for one",
            (ProgramSchemaFixture.ALL_TABLES_AT_CURRENT_VERSION + "room_master_table").sorted(),
            tablesOf(after)
        )
    }

    @Test
    fun everyRetainedRowSurvivesTheUpgradeUnchanged() {
        val before = versionSevenDatabase()
        val after = migratedDatabase()

        // The posture track's row is compared through an explicit projection, because its *row
        // identity* is renamed by this step (`cycleNumber`/`day` → `trackCycle`/`trackDay`) while every
        // value it holds must survive: the rename is the claim, and a `SELECT *` would compare two
        // different column sets instead of the values.
        assertEquals(
            "the track's row keeps every value it held; only the two identity columns are renamed. The " +
                "projections are compared by *value* and in the same order, because the column names " +
                "differing is the rename itself",
            before.rows("SELECT `cycleNumber`, `day`, `isCompleted`, `completionDate`, `focusArea` " +
                "FROM `posture_session_progress`").map { row -> row.values.toList() },
            after.rows("SELECT `trackCycle`, `trackDay`, `isCompleted`, `completionDate`, `focusArea` " +
                "FROM `posture_session_progress`").map { row -> row.values.toList() }
        )

        val retainedRows = listOf("body_weight_log", "meal_cycles", "meals", "shopping_items")
        for (table in retainedRows) {
            val expected = before.rows("SELECT * FROM `$table`")
            assertTrue("the fixture wrote a row into `$table`", expected.isNotEmpty())
            assertEquals("`$table` rows survive the upgrade byte for byte", expected, after.rows("SELECT * FROM `$table`"))
        }
    }

    @Test
    fun theTrackRowIsRenamedAndNotRewritten() {
        // The one table this stage changes shape. The claim is narrower than "the row is still there":
        // it is that the row is the SAME row — same cycle, same day, same completion stamp, same focus
        // area — under its own vocabulary. A drop-and-recreate without the copy would leave the table
        // present and empty, which is the failure this test exists to catch.
        val database = migratedDatabase()

        assertEquals("the track's rows were copied, not discarded", 1, database.count("posture_session_progress"))
        assertEquals(
            "and the copied row is the one the device held: cycle and day became the track's own names",
            listOf("2|7|1|1700000000000|UPPER_BACK"),
            database.strings(
                "SELECT trackCycle || '|' || trackDay || '|' || isCompleted || '|' || completionDate " +
                    "|| '|' || focusArea FROM `posture_session_progress`"
            )
        )
        assertEquals(
            "the renamed identity is still the primary key, in the same order",
            listOf("trackCycle", "trackDay"),
            database.primaryKey("posture_session_progress")
        )
        assertEquals(
            "the old column names are gone, so nothing can read the track through the retired vocabulary",
            listOf("trackCycle", "trackDay", "isCompleted", "completionDate", "focusArea"),
            database.columnNames("posture_session_progress")
        )
    }

    @Test
    fun theRetiredTablesAndTheirRowsAreGone() {
        val after = migratedDatabase()

        for (table in ProgramSchemaFixture.RETIRED_TABLES) {
            assertFalse(
                "`$table` is dropped by §30 step 15, not kept and not renamed",
                after.tableNames().contains(table)
            )
        }
        assertEquals(
            "and the database holds no table outside the retained and target sets, so nothing was " +
                "left behind under another name",
            (ProgramSchemaFixture.ALL_TABLES_AT_CURRENT_VERSION + "room_master_table").sorted(),
            tablesOf(after)
        )
    }

    @Test
    fun noLegacyRowBecomesATargetRow() {
        // The blueprint's "no legacy program/history migration is required" read as a measurement: the
        // upgrade drops the legacy rows and writes **nothing** into the target schema. A conversion —
        // a `UserProgress` row becoming a Session, a legacy `set_log` row becoming a target set — would
        // show up here as a non-empty target table.
        val database = migratedDatabase()

        for (table in ProgramSchemaFixture.TABLES) {
            assertEquals(
                "`$table` is empty after the upgrade: the retired rows were not reinterpreted as target " +
                    "rows (the target history starts with the target runtime)",
                0,
                database.count(table)
            )
        }
    }

    @Test
    fun theUpgradeDoesNotUseADestructiveRecreation() {
        // The other half of "a real migration, not a recreation": the database must never be dropped and
        // rebuilt, because that would take the retained rows with it. Room's destructive fallback is the
        // switch that does exactly that, so its absence from the builder is the guard.
        val source = java.io.File("src/main/java/com/monkfitness/app/data/local/AppDatabase.kt").let {
            if (it.isFile) it else java.io.File("app/src/main/java/com/monkfitness/app/data/local/AppDatabase.kt")
        }.readText()

        assertFalse(
            "the builder must not accept a destructive fallback: a device that cannot migrate must fail " +
                "loudly rather than lose the retained rows",
            source.contains("fallbackToDestructiveMigration")
        )
    }

    @Test
    fun theUpgradeRewritesNoRetainedTableDefinitionButTheTracks() {
        val before = versionSevenDatabase().masterSql()
        val after = migratedDatabase().masterSql()

        for (table in ProgramSchemaFixture.RETAINED_TABLES.filterNot { it == "posture_session_progress" }) {
            assertNotNull("`$table` existed before the upgrade", before[table])
            assertEquals(
                "`$table` is neither reshaped nor renamed by the upgrade",
                storedForm(before.getValue(table)),
                storedForm(after.getValue(table))
            )
        }
        assertEquals(
            "and the track is the one retained table this stage rewrites — its identity columns are " +
                "renamed, and nothing else about it changes. The shape is read back from the engine " +
                "rather than compared as a DDL string, because the engine's own spelling of that string " +
                "is not the claim",
            listOf("trackCycle", "trackDay", "isCompleted", "completionDate", "focusArea"),
            migratedDatabase().columnNames("posture_session_progress")
        )
        assertEquals(
            "with the same affinities the columns always had",
            listOf("INTEGER", "INTEGER", "INTEGER", "INTEGER", "TEXT"),
            listOf("trackCycle", "trackDay", "isCompleted", "completionDate", "focusArea")
                .map { column -> migratedDatabase().columnType("posture_session_progress", column) }
        )
        assertEquals(
            "the retained tables' indices are the same ones afterwards",
            indicesOfLegacyTables(before),
            indicesOfLegacyTables(after)
        )
    }

    /** The indices of the tables the upgrade keeps, which it may neither drop nor redefine. */
    private fun indicesOfLegacyTables(schema: Map<String, String>): Map<String, String> =
        schema
            .filterKeys { name ->
                name.startsWith("index_") &&
                    ProgramSchemaFixture.RETAINED_TABLES.any { table -> name.startsWith("index_${table}_") }
            }
            .mapValues { storedForm(it.value) }

    @Test
    fun theStageOneAdaptivePersistenceIsGoneAndTheTargetOneIsWhatRemains() {
        // §30 step 15 inverted this claim. It used to prove the Stage-1 tables were still *writable*
        // after the upgrade — the point of the coexisting generations. The coexistence is over: the
        // Stage-1 tables are dropped and the target ones are the only adaptive persistence there is, so
        // the claim becomes that a write lands in the target tables and nowhere else.
        val database = migratedDatabase()

        for (retired in listOf("family_progression_state", "adaptive_decision_record")) {
            assertFalse("`$retired` is dropped", database.tableNames().contains(retired))
        }

        // The target family state is owned by a revision, so the write needs one to exist: the FK is
        // part of what makes the target table the *owned* one the Stage-1 table never was.
        ProgramGraphInserts.insertCompleteProgram(database, "1")

        database.exec(
            "INSERT INTO `program_family_progression_state` (`revisionId`, `familyId`, " +
                "`progressionLevel`, `adaptationState`, `currentExerciseId`, `updatedAt`) " +
                "VALUES ('revision-1', 'squat-family', 1, 'PROGRESS', 'squats', 1700000000000)"
        )
        assertEquals(
            "the target family state is the one an upgrade leaves writable — the graph fixture's own " +
                "row plus the one just written",
            2,
            database.count("program_family_progression_state")
        )
        assertEquals(
            "and it is keyed by the revision *identity*, not by the retired revision integer",
            "TEXT",
            database.columnType("program_family_progression_state", "revisionId")
        )
        assertEquals(
            "the target decision table is the only audit trail there is — the one row the graph " +
                "fixture wrote, and nothing the upgrade invented on its way past the retired one",
            1,
            database.count("program_adaptive_decision_record")
        )
    }

    @Test
    fun theUpgradeLeavesRoomsOwnBookkeepingToRoom() {
        val database = migratedDatabase()

        assertEquals(
            "the migration does not touch the identity Room rewrites after a successful upgrade",
            "a5aeaf5a669d0f822992dc24665fa95f",
            database.scalar("SELECT identity_hash FROM room_master_table")
        )
    }

    @Test
    fun theMigratedSchemaIsTheSchemaRoomExpects() {
        val database = migratedDatabase()
        val schema = database.masterSql()

        for (table in ProgramSchemaFixture.TABLES) {
            assertEquals(
                "`$table` is created exactly as Room's generated DDL declares it at the current version",
                storedForm(ProgramSchemaFixture.expectedCurrentTableDdl(table)),
                storedForm(schema.getValue(table))
            )
        }
        val expectedIndices = ProgramSchemaFixture.TABLES.flatMap { table ->
            ProgramSchemaFixture.INDEXES.getValue(table).map { ProgramSchemaFixture.expectedIndexDdl(table, it) }
        }
        assertEquals(
            "every declared index exists, and no undeclared one does",
            expectedIndices.associateBy { nameOfIndex(it) }.mapValues { storedForm(it.value) },
            schema
                .filterKeys { name -> ProgramSchemaFixture.TABLES.any { name.startsWith("index_${it}_") } }
                .mapValues { storedForm(it.value) }
        )
    }

    private fun nameOfIndex(ddl: String): String =
        ddl.substringAfter("IF NOT EXISTS `").substringBefore("`")

    @Test
    fun theForeignKeysTheEngineRecordsAreTheOwnershipGraphOfTheArchitecture() {
        val database = migratedDatabase()

        for (table in ProgramSchemaFixture.TABLES) {
            // The engine lists a table's keys in its own order, which carries no meaning, so the
            // comparison is by child column: the graph, not the sequence it was written in.
            assertEquals(
                "`$table`'s foreign keys as SQLite records them",
                ProgramSchemaFixture.FOREIGN_KEYS.getValue(table).map {
                    SqliteTestDatabase.ForeignKey(
                        childColumn = it.childColumn,
                        parentTable = it.parentTable,
                        parentColumn = it.parentColumn,
                        onDelete = it.onDelete,
                        onUpdate = "NO ACTION"
                    )
                }.sortedBy { it.childColumn },
                database.foreignKeys(table).sortedBy { it.childColumn }
            )
        }
    }

    @Test
    fun everyTargetIdentityIsItsOwnPrimaryKeyInTheEngine() {
        val database = migratedDatabase()

        for (table in ProgramSchemaFixture.TABLES) {
            assertEquals(
                "`$table`'s primary key as SQLite records it",
                ProgramSchemaFixture.PRIMARY_KEYS.getValue(table),
                database.primaryKey(table)
            )
        }
    }

    @Test
    fun everyTargetColumnHasTheTypeAndNullabilityTheContractDeclares() {
        val database = migratedDatabase()

        for (table in ProgramSchemaFixture.TABLES) {
            assertEquals(
                "`$table`'s columns are exactly the declared ones, at the current version",
                ProgramSchemaFixture.columnsNow(table).map { it.name },
                database.columnNames(table)
            )
            for (column in ProgramSchemaFixture.columnsNow(table)) {
                assertEquals(
                    "`$table`.`${column.name}`'s declared type",
                    column.type,
                    database.columnType(table, column.name)
                )
                val notNull = database.rows(
                    "SELECT \"notnull\" FROM pragma_table_info('$table') WHERE name = ?",
                    column.name
                ).single().getValue("notnull")
                assertEquals(
                    "`$table`.`${column.name}`'s nullability",
                    if (column.nullable) "0" else "1",
                    notNull
                )
            }
        }
    }

    @Test
    fun theUniqueIndicesTheEngineRecordsAreTheOnesTheArchitectureRequires() {
        val database = migratedDatabase()

        for (table in ProgramSchemaFixture.TABLES) {
            val expected = ProgramSchemaFixture.INDEXES.getValue(table)
                .filter { it.unique }
                .associate { it.name to it.columns }
            assertEquals(
                "`$table`'s unique indices as SQLite records them",
                expected,
                database.uniqueIndexes(table)
            )
        }
    }

    @Test
    fun theTargetSetLogIsTheOnlySetLogAfterTheUpgrade() {
        // §30 step 15 inverted this claim: it used to be about two independent set logs coexisting.
        // One is retired, so the claim is that there is exactly one — and that it is the target one.
        val database = migratedDatabase()
        ProgramGraphInserts.insertCompleteProgram(database, "1")

        assertFalse(
            "the shipped logging table is dropped, so nothing can write a second set log",
            database.tableNames().contains("set_log")
        )
        assertEquals("the target set log holds the confirmed set", 1, database.count("program_set_log"))
        assertEquals(
            "and the row names the session exercise it belongs to — there is no date-keyed shape left",
            "session-exercise-1",
            database.scalar("SELECT sessionExerciseId FROM `program_set_log`")
        )
        assertEquals(
            "the target table's columns are exactly the owned ones",
            listOf("setLogId", "sessionExerciseId", "setIndex", "completedReps", "durationSeconds", "performedAt"),
            database.columnNames("program_set_log")
        )
    }

    @Test
    fun aPrescriptionSurvivesTheDatabaseUnchangedAndPerSet() {
        val database = migratedDatabase()
        ProgramGraphInserts.insertCompleteProgram(database, "1")
        database.exec(
            "INSERT INTO `program_exercise` (`programExerciseId`, `programDayId`, `position`, " +
                "`exerciseId`, `prescriptionDimension`, `perSetTargets`, `origin`, `isPinned`) " +
                "VALUES ('plan-exercise-timed', 'day-1', 2, 'plank', 'TIME_BASED', '30,30,45', " +
                "'USER_AUTHORED', 1)"
        )

        assertEquals(
            "12 / 10 / 8 / 6 is stored as four targets",
            "12,10,8,6",
            database.scalar(
                "SELECT perSetTargets FROM `program_exercise` WHERE programExerciseId = 'plan-exercise-1'"
            )
        )
        assertEquals(
            "30 / 30 / 45 seconds is stored as three",
            "30,30,45",
            database.scalar(
                "SELECT perSetTargets FROM `program_exercise` WHERE programExerciseId = 'plan-exercise-timed'"
            )
        )
        assertEquals(
            "and the dimension is stored beside them",
            listOf("REP_BASED", "TIME_BASED"),
            database.strings("SELECT prescriptionDimension FROM `program_exercise` ORDER BY position")
        )
        assertEquals(
            "the captured presentation keeps its own copy of the prescription",
            "12,10,8,6",
            database.scalar("SELECT perSetTargets FROM `session_snapshot_exercise`")
        )
        assertEquals(
            "and so does the occurrence that ran",
            "12,10,8,6",
            database.scalar("SELECT perSetTargets FROM `session_exercise`")
        )
    }

    @Test
    fun aRestDaySlotAndAMissedSlotCarryNoPerformanceRows() {
        val database = migratedDatabase()
        ProgramGraphInserts.insertCompleteProgram(database, "1")
        database.exec(
            "INSERT INTO `program_day` (`programDayId`, `revisionId`, `position`, `type`, `name`) " +
                "VALUES ('day-rest', 'revision-1', 2, 'REST', NULL)"
        )
        database.exec(
            "INSERT INTO `program_workout_slot` (`slotId`, `programId`, `revisionId`, `programDayId`, " +
                "`plannedFor`, `status`, `completedAt`) VALUES ('slot-rest', 'program-1', " +
                "'revision-1', 'day-rest', '2026-09-19', 'PLANNED', NULL)"
        )
        database.exec(
            "INSERT INTO `program_workout_slot` (`slotId`, `programId`, `revisionId`, `programDayId`, " +
                "`plannedFor`, `status`, `completedAt`) VALUES ('slot-missed', 'program-1', " +
                "'revision-1', 'day-rest', '2026-09-17', 'MISSED', NULL)"
        )

        assertEquals(
            "a rest day is an opportunity, not a workout: it may exist as a slot without a session (§20)",
            0,
            database.scalar(
                "SELECT COUNT(*) FROM `workout_session` WHERE slotId IN ('slot-rest', 'slot-missed')"
            )!!.toInt()
        )
        assertEquals(
            "a missed opportunity records no amount at all — there is no column to zero (§12)",
            listOf(
                "slotId", "programId", "revisionId", "programDayId", "plannedFor", "status", "completedAt",
                "targetOccurrenceKey"
            ),
            database.columnNames("program_workout_slot")
        )
        assertEquals(
            "a MISSED slot is still a row that says it did not happen",
            listOf("PLANNED", "MISSED"),
            database.strings(
                "SELECT status FROM `program_workout_slot` WHERE slotId IN ('slot-rest', 'slot-missed') " +
                    "ORDER BY plannedFor DESC"
            )
        )
    }

    @Test
    fun aCancelledSessionKeepsItsPartialWorkAndDoesNotCompleteItsSlot() {
        val database = migratedDatabase()
        ProgramGraphInserts.insertCompleteProgram(database, "1")
        database.exec("UPDATE `workout_session` SET status = 'CANCELLED', finishedAt = 1700000004000")
        database.exec("UPDATE `program_workout_slot` SET status = 'MISSED'")

        assertEquals("a cancelled session is history, not a deletion", 1, database.count("workout_session"))
        assertEquals(
            "the set it did confirm stays recorded as partial exposure (§12)",
            1,
            database.count("program_set_log")
        )
        assertEquals(
            "and cancelling did not complete the slot it attempted",
            "MISSED",
            database.scalar("SELECT status FROM `program_workout_slot` WHERE slotId = 'slot-1'")
        )
        assertEquals(
            "a cancelled session is not a finished workout",
            "CANCELLED",
            database.scalar("SELECT status FROM `workout_session` WHERE sessionId = 'session-1'")
        )
    }

    @Test
    fun theUpgradeIsTheSameStatementsAVersionSevenDeviceExecutes() {
        // The rewrite-proof behind the tests above: they ran the production migration objects, not a
        // copy of their SQL. This asserts the objects are the ones AppDatabase registers — as one
        // unbroken chain — and that a real engine accepts every statement they contain.
        assertEquals(7, AppDatabase.MIGRATION_7_8.startVersion)
        assertEquals(8, AppDatabase.MIGRATION_7_8.endVersion)
        assertEquals(8, AppDatabase.MIGRATION_8_9.startVersion)
        assertEquals(9, AppDatabase.MIGRATION_8_9.endVersion)
        assertEquals(9, AppDatabase.MIGRATION_9_10.startVersion)
        assertEquals(10, AppDatabase.MIGRATION_9_10.endVersion)
        assertEquals(10, AppDatabase.MIGRATION_10_11.startVersion)
        assertEquals(11, AppDatabase.MIGRATION_10_11.endVersion)
        assertEquals(11, AppDatabase.MIGRATION_11_12.startVersion)
        assertEquals(12, AppDatabase.MIGRATION_11_12.endVersion)

        val database = SqliteTestDatabase.inMemory()
        database.execAll(LegacyV7Schema.TABLE_STATEMENTS)
        try {
            database.migrate(AppDatabase.MIGRATION_7_8)
            database.migrate(AppDatabase.MIGRATION_8_9)
            database.migrate(AppDatabase.MIGRATION_9_10)
            database.migrate(AppDatabase.MIGRATION_10_11)
            database.migrate(AppDatabase.MIGRATION_11_12)
            database.migrate(AppDatabase.MIGRATION_12_13)
        } catch (failure: SQLException) {
            throw AssertionError("the migration failed on a real engine: ${failure.message}")
        }
        assertEquals(
            "every target table exists after the chain executed",
            ProgramSchemaFixture.TABLES.size,
            database.tableNames().count { it in ProgramSchemaFixture.TABLES }
        )
        assertEquals(
            "and the last step put the columns it adds on the table it adds them to",
            ProgramSchemaFixture.columnsNow("program_revision").map { it.name },
            database.columnNames("program_revision")
        )
        assertEquals(
            "including the adaptive window bookkeeping the window step appended to the family-state table",
            ProgramSchemaFixture.columnsNow("program_family_progression_state").map { it.name },
            database.columnNames("program_family_progression_state")
        )
        assertEquals(
            "and the last step leaves the database with the retained tables and the target ones only",
            (ProgramSchemaFixture.ALL_TABLES_AT_CURRENT_VERSION + "room_master_table").sorted(),
            database.tableNames().filterNot { it.startsWith("sqlite_") }.sorted()
        )
    }

    @Test
    fun targetIdentityMigrationPreservesAPopulatedLegacySlotAndItsSessions() {
        val database = SqliteTestDatabase.inMemory()
        database.execAll(LegacyV7Schema.TABLE_STATEMENTS)
        database.migrate(AppDatabase.MIGRATION_7_8)
        database.migrate(AppDatabase.MIGRATION_8_9)
        database.migrate(AppDatabase.MIGRATION_9_10)
        database.migrate(AppDatabase.MIGRATION_10_11)
        database.migrate(AppDatabase.MIGRATION_11_12)
        ProgramGraphInserts.insertCompleteProgram(database, "v12", targetOccurrenceKey = null)
        val slotBefore = database.rows(
            "SELECT `slotId`, `programId`, `revisionId`, `programDayId`, `plannedFor`, `status`, " +
                "`completedAt` FROM `program_workout_slot` WHERE `slotId` = 'slot-v12'"
        ).single()
        val sessionsBefore = database.rows("SELECT * FROM `workout_session`")

        database.migrate(AppDatabase.MIGRATION_12_13)

        assertEquals(
            "the existing row and every old value survive byte for byte",
            slotBefore,
            database.rows(
                "SELECT `slotId`, `programId`, `revisionId`, `programDayId`, `plannedFor`, `status`, " +
                    "`completedAt` FROM `program_workout_slot` WHERE `slotId` = 'slot-v12'"
            ).single()
        )
        assertNull(
            "a legacy slot has no artificial target identity",
            database.scalar("SELECT `targetOccurrenceKey` FROM `program_workout_slot` WHERE `slotId` = 'slot-v12'")
        )
        assertEquals("its session rows are untouched", sessionsBefore, database.rows("SELECT * FROM `workout_session`"))
    }

    @Test
    fun theFocusCorrectionUpgradesAPopulatedVersionNineDatabaseWithoutInventingAGoal() {
        val database = versionNineDatabase()

        // The version-9 row set: a Program and its revision, written before Goals & Focus had
        // anywhere to be stored.
        database.exec(
            "INSERT INTO `program` (`programId`, `name`, `description`, `source`, `lifecycleStatus`, " +
                "`currentRevisionId`, `createdAt`, `updatedAt`, `plannedStartDate`, `actualStartDate`, " +
                "`archivedAt`) VALUES ('program-9', 'Program', '', 'USER', 'NOT_STARTED', " +
                "'revision-9', 1700000000000, 1700000000000, NULL, NULL, NULL)"
        )
        database.exec(
            "INSERT INTO `program_revision` (`revisionId`, `programId`, `revisionNumber`, `mode`, " +
                "`durationType`, `durationDays`, `scheduleType`, `scheduleWeekdays`, `createdAt`, " +
                "`scheduleSessionsPerWeek`) VALUES ('revision-9', 'program-9', 1, 'GENERATED', " +
                "'INDEFINITE', NULL, 'FLEXIBLE_PER_WEEK', NULL, 1700000000000, 3)"
        )
        val revisionBefore = database.rows("SELECT * FROM `program_revision`").single()
        val schemaBefore = database.masterSql()

        database.migrate(AppDatabase.MIGRATION_9_10)

        val revisionAfter = database.rows("SELECT * FROM `program_revision`").single()
        assertEquals(
            "the row the version-9 database held keeps every value it held",
            revisionBefore,
            revisionAfter.filterKeys { it in revisionBefore.keys }
        )
        assertEquals(
            "and the correction leaves the goal and its targets empty rather than filling in a " +
                "plausible goal: the schema cannot know what the user was building for, and a default " +
                "would state a configuration nobody chose",
            listOf(null, null),
            listOf(revisionAfter["focusGoal"], revisionAfter["focusTargets"])
        )
        assertEquals(
            "no table, index or bookkeeping entry other than the corrected table is rewritten",
            schemaBefore.filterKeys { it != "program_revision" },
            database.masterSql().filterKeys { it != "program_revision" }
        )
        assertEquals(
            "the corrected table gains exactly the columns this step adds, appended",
            ProgramSchemaFixture.columnsNow("program_revision").map { it.name },
            database.columnNames("program_revision")
        )
        assertEquals(
            "and the shipped tables the device already had are still there, untouched",
            "pushup",
            database.scalar("SELECT currentExerciseId FROM `family_progression_state`")
        )
    }

    @Test
    fun theCorrectionUpgradesAPopulatedVersionEightDatabaseWithoutInventingAFrequency() {
        val database = versionEightDatabase()

        // The version-8 row set: a Program and its revision with the schedule form and no frequency,
        // because at version 8 there was nowhere to store one.
        database.exec(
            "INSERT INTO `program` (`programId`, `name`, `description`, `source`, `lifecycleStatus`, " +
                "`currentRevisionId`, `createdAt`, `updatedAt`, `plannedStartDate`, `actualStartDate`, " +
                "`archivedAt`) VALUES ('program-1', 'Program', '', 'USER', 'NOT_STARTED', " +
                "'revision-1', 1700000000000, 1700000000000, NULL, NULL, NULL)"
        )
        database.exec(
            "INSERT INTO `program_revision` (`revisionId`, `programId`, `revisionNumber`, `mode`, " +
                "`durationType`, `durationDays`, `scheduleType`, `scheduleWeekdays`, `createdAt`) " +
                "VALUES ('revision-1', 'program-1', 1, 'MANUAL', 'FIXED_DAYS', 30, " +
                "'FLEXIBLE_PER_WEEK', NULL, 1700000000000)"
        )
        val revisionBefore = database.rows("SELECT * FROM `program_revision`").single()
        val schemaBefore = database.masterSql()

        database.migrate(AppDatabase.MIGRATION_8_9)

        val revisionAfter = database.rows("SELECT * FROM `program_revision`").single()
        assertEquals(
            "the row the version-8 database held keeps every value it held",
            revisionBefore,
            revisionAfter.filterKeys { it in revisionBefore.keys }
        )
        assertEquals(
            "and the correction leaves its frequency empty rather than filling in a plausible number: " +
                "the schema cannot know what the user trained at, and a default would state a schedule " +
                "nobody chose",
            listOf(null),
            listOf(revisionAfter["scheduleSessionsPerWeek"])
        )
        assertEquals(
            "no table, index or bookkeeping entry other than the corrected table is rewritten",
            schemaBefore.filterKeys { it != "program_revision" },
            database.masterSql().filterKeys { it != "program_revision" }
        )
        assertEquals(
            "the corrected table gains exactly the one column this step adds, appended",
            (
                ProgramSchemaFixture.COLUMNS.getValue("program_revision") +
                    ProgramSchemaFixture.columnsAddedBy("MIGRATION_8_9", "program_revision")
                ).map { it.name },
            database.columnNames("program_revision")
        )
        assertEquals(
            "the legacy rows the database held before the correction are untouched too",
            "pushup",
            database.scalar("SELECT currentExerciseId FROM `family_progression_state`")
        )
    }
}
